# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
#image: registry.gitlab.com/pages/hugo:latest
image: hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - eval `ssh-agent`
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

stages:
  - test
  - draft
  - deploy
  
test:
  script:
  - hugo
  except:
  - master
#  - develop

draft:
  script:
    - hugo
    - rsync -au -e "ssh -oStrictHostKeyChecking=no" public web-updater@www-intra:/home/httpd/html/test/
#  only:
#    - develop
    
deploy:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
