image: hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - creation
  - test 
  - del_test
  - deploy
  
before_script:
  - eval `ssh-agent`
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

file_creation:
  stage: creation
  script:
    - 'if [ -n "$FILENAME" ]; then'
    - hugo new post/$FILENAME.md
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git add content/post/$FILENAME.md
    - 'git commit -m "new content file creation: post/$FILENAME.md"'
    - git -c core.sshCommand="ssh -oStrictHostKeyChecking=no" push gitlab@www-intra.cns.s.u-tokyo.ac.jp:cns-netadmin/cns-hp.git HEAD:${CI_COMMIT_REF_NAME}
    - fi
  only:
    - /^draft_.*$/

draft:
  stage: test
  script:
    - 'hugo -b https://www.cns.s.u-tokyo.ac.jp/test/${CI_COMMIT_REF_NAME}'
    - rsync -au -e "ssh -oStrictHostKeyChecking=no" public/ web-updater@www-intra:/home/httpd/html/test/${CI_COMMIT_REF_NAME}
  only:
    - /^draft_.*$/

delete_testpage:
  stage: del_test
  script:
    - ssh -oStrictHostKeyChecking=no web-updater@www-intra rm -r /home/httpd/html/test/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
  only: 
    refs:
      - merge_requests
    variables:
      - $CI_COMMIT_REF_NAME == /^draft_.*$/
  
deploy:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master